# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new internal test to Apple Testflight"
  lane :beta do
    unlock_keychain
    increment_build_number(
      xcodeproj: "ios/htwgCampus.xcodeproj"
    )
    commit_version_bump(
      message: "Changed iOS build number"
    )
    match(type: "appstore")
    gym(scheme:"htwgCampus")
    pilot
  end
end
