# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new build to iTunes Connect"
  lane :build do
    increment_build_number
    commit_version_bump(
      message: "🤖 Changed build number for 🍎 [skip ci]"
    )
    push_to_git_remote(
      remote: "origin",
      local_branch: "development",
      remote_branch: "development",
      tags: false
    )
    match(type: "appstore")
    gym(
        project: "htwgCampus.xcodeproj",
        export_options: {
            method: "app-store",
            provisioningProfiles: {
              "org.htwg-konstanz.htwgCampus" => "match AppStore org.htwg-konstanz.htwgCampus"
            }
          }
    )
    pilot
  end
end
