# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new internal test to Apple Testflight"
  lane :beta do
    unlock_keychain
    increment_build_number
    commit_version_bump(
      message: "Changed iOS build number"
    )
    match(type: "appstore")
    gym(
        scheme:"htwgCampus",
        export_method: "app-store",
        xcargs: "PROVISIONING_PROFILE=f90e60ad-bff0-4d9c-af1f-571c99799b39"
    )
    pilot
  end
end
