# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
   desc "Deploy a new internal test version to the Google Play Store"
    lane :internal do
    increment_version_code(
        gradle_file_path: "./app/build.gradle"
    )
    gradle(
        task: "assemble",
        build_type: "Release"
    )
    supply(
        track: "internal",
        apk: "/Users/vagrant/git/android/app/build/outputs/apk/release/app-release.apk"
    )
    end
    desc "Deploy a new beta test version to the Google Play Store"
        lane :beta do
        increment_version_code(
            gradle_file_path: "./app/build.gradle"
        )
        gradle(
            task: "assemble",
            build_type: "Release"
        )
        supply(
            track: "alpha",
            apk: "/Users/vagrant/git/android/app/build/outputs/apk/release/app-release.apk"
        )
    end
end
